--[[> Copyright Goldcore & XenusSoft 2020 <]]--
--[[>  Use of file is allowed. <]]--
function bottom()
  local titleb = "(C)Goldcore 2020-2021"
  term.setTextColor(colors.lightGray)
  term.setCursorPos(wm - (#titleb/2), h)
  term.write(titleb)
end
parallel.waitForAny(function()
  --< code here >--
  shell.run("/system/cload.lua")
  --sleep(8) -- remove this, just for show
  sleep(1)
end, function()
  local title = "Starting COSC..." -- Change title to what you perfer for the bootup.
  w, h = term.getSize()
  wm, hm = w/2, h/2
  term.setBackgroundColor(colors.white)
  term.setTextColor(colors.black)
  term.setCursorPos(wm - (#title/2), hm)
  term.clear()
  term.write(title)
  bottom()
  sleep(0.1)
  term.setBackgroundColor(colors.lightGray)
  term.setTextColor(colors.gray)
  term.setCursorPos(wm - (#title/2), hm)
  term.clear()
  term.write(title)
  bottom()
  sleep(0.1)
  term.setBackgroundColor(colors.gray)
  term.setTextColor(colors.lightGray)
  term.setCursorPos(wm - (#title/2), hm)
  term.clear()
  term.write(title)
  bottom()
  sleep(0.1)
  term.setBackgroundColor(colors.black)
  term.setTextColor(colors.white)
  term.setCursorPos(wm - (#title/2), hm)
  term.clear()
  term.write(title)
  bottom()
  sleep(1)
  while true do
    w, h = term.getSize()
    wm, hm = w/2, h/2
    term.clear()
    for i = 1, 2 do
      term.setBackgroundColor(colors.black)
      term.setTextColor(colors.lightGray)
      term.setCursorPos(wm - (#title/2), hm)
      term.write(title)
	  bottom()
      sleep(0.025)
      term.clear()
      term.setBackgroundColor(colors.black)
      term.setTextColor(colors.gray)
      term.setCursorPos(wm - (#title/2), hm)
      term.write(title)
	  bottom()
      sleep(0.025)
      term.clear()
      term.setBackgroundColor(colors.black)
      term.setTextColor(colors.lightGray)
      term.setCursorPos(wm - (#title/2), hm)
      term.write(title)
	  bottom()
      sleep(0.025)
      term.clear()
      term.setBackgroundColor(colors.black)
      term.setTextColor(colors.white)
      term.setCursorPos(wm - (#title/2), hm)
      term.write(title)
	  bottom()
      sleep(0.025)
    end
    term.setBackgroundColor(colors.black)
    term.setTextColor(colors.white)
    term.setCursorPos(wm - (#title/2), hm)
    term.clear()
    term.write(title)
	bottom()
    sleep(2)
  end
end)
term.clear()
term.setTextColor(colors.white)
term.setCursorPos(1, 1)
