reg.software.Goldcore.Setup.OOBEInProgress = 1
cosc.saveReg("software")
term.redirect(term.native())
local expect = require("cc.expect").expect
local w,h = term.getSize()
local topBar = window.create(term.current(),1,1,w,1,true)
local content = window.create(term.current(),1,2,w,h,true)
function uiRead(w, string_prompt, string_charReplace, table_history, function_complete, string_startWith)
    expect(1, w, "table")
    if not w.getSize then error("not a window", 0) end
    expect(2, string_prompt, "string")
    expect(3, string_charReplace, "nil", "string")
    expect(4, table_history, "nil", "table")
    expect(5, table_history, "nil", "function")
    expect(6, string_startWith, "nil", "string")
    local w, h = w.getSize()
    local wm, hm = (w/2), (h/2)
    w.setBackgroundColor(colors.cyan)
    w.setTextColor(colors.white)
    w.clear()
    w.setCursorPos(1,1)
    w.setBackgroundColor(colors.gray)
    w.setTextColor(colors.white)
    w.setCursorPos(1, h - 1)
    w.clearLine()
    local o = read(string_charReplace, table_history, function_complete, string_startWith)
    w.setBackgroundColor(colors.black)
    w.setTextColor(colors.white)
    w.clear()
    w.setCursorPos(1,1)
    return o
end
function updateTopBar(txt)
term.redirect(topBar)
topBar.setBackgroundColor(term.isColor() and colors.cyan or colors.gray)
topBar.setTextColor(colors.white)
topBar.clear()
topBar.setCursorPos(1,1)
topBar.write(txt)
term.redirect(content)
end
function clearContent()
content.setBackgroundColor(term.isColor() and colors.gray or colors.black)
content.setTextColor(term.isColor() and colors.black or colors.white)
content.clear()
content.setCursorPos(1,1)
end
content.setBackgroundColor(colors.cyan)
coroutine.yield()
clearContent()
term.redirect(content)
coroutine.yield()
updateTopBar("Intro")
textutils.slowPrint("Welcome to COSC!")
textutils.slowPrint("It's time to do some quick setup.")
textutils.slowPrint("Ok, Let's get right into it.")
sleep(2)
updateTopBar("User")
clearContent()
print("Create a user account.")
write("Username: ")
local usrn = read()
write("Password: ")
local psk = read("*")
cosc.createUser(usrn,psk)
clearContent()
reg.software.Goldcore.Setup.OOBEComplete = 1
reg.software.Goldcore.Setup.OOBEInProgress = 0
reg.software.Goldcore.Setup.RestartSetup = 0
cosc.saveReg("software")
